export interface Observation {
X?: number,
Y?: number,
additionalPhoto? :string,
cdGroupOP?: number,
cdNom?: number,
cdPhotoPrincipal?: number,
cdRef?: number,
cdSig? :string,
commentaire? :string,
dateCrea? :string,
dateModif? :string,
groupSimple? :string,
idData?: number,
idExpertise?: number,
idUtilisateur?: number,
isTagged? :string,
isValidated? :string,
nomComplet? :string,
nomCompletHtml? :string,
nomCommuns? :string,
photos :[ {
    cdPhoto?: number,
    fileName? :string,
    inpnFileUri? :string,
    thumbnailFileUri? :string,
    dateCrea? :string,
    dateModif? :string,
    isTreated? :string,
    isValidated? :string,
}],

validation:{StatusComment? :string,
    dateStatus? :string,
    idStatus?: number,
    idValidateur?: number,
    idValidation?: number,
    lbStatus? :string}
}
